import {useState} from 'react';
import {supabase,supabaseConfigured} from '../lib/supabase';
const steps=['در انتظار پرداخت','تأیید سفارش','آماده ارسال','ارسال شد','تحویل داده شد'];

export default function Track({initialId=''}){const[id,setId]=useState(initialId),[order,setOrder]=useState(null),[searched,setSearched]=useState(false),[error,setError]=useState('');
const show=async e=>{e.preventDefault();setError('');setOrder(null);setSearched(true);if(!supabaseConfigured)return setError('اتصال فروشگاه به دیتابیس تنظیم نشده است.');const {data,error:err}=await supabase.rpc('get_order_by_tracking',{p_order_number:id.trim()});if(err)setError(err.message);else setOrder(data)};
const idx=order?Math.max(0,steps.indexOf(order.status)):0;const paymentResult=new URLSearchParams(location.search).get('payment');
return <main className="track-page"><div className="checkout-title"><h1>پیگیری سفارش</h1><p>شماره سفارش را وارد کنید.</p></div><form onSubmit={show} className="track-form"><input value={id} onChange={e=>setId(e.target.value)} placeholder="مثلاً YL-12345678" required/><button className="btn">پیگیری</button></form>
{paymentResult==='success'&&<div className="success">پرداخت با موفقیت تأیید شد و سفارش شما ثبت نهایی شد.</div>}{paymentResult==='failed'&&<div className="error">پرداخت تکمیل نشد. در صورت کسر وجه، وضعیت تراکنش پس از بررسی بانکی به‌روزرسانی می‌شود.</div>}{error&&<div className="error">{error}</div>}
{order?<div className="track-card"><div className="track-top"><div><h2>سفارش {order.order_number}</h2><small>{new Date(order.created_at).toLocaleString('fa-IR')}</small></div><div className="status">{order.status}</div></div><div className="track-steps">{steps.map((s,i)=><div className={i<=idx?'track-step done':'track-step'} key={s}><span>{i<idx?'✓':i+1}</span><b>{s}</b></div>)}</div><div className="track-info"><p>مشتری: {order.customer?.name}</p><p>شهر: {order.customer?.city}</p><p>مبلغ: {Number(order.total).toLocaleString('fa-IR')} تومان</p><p>تعداد اقلام: {(order.items||[]).reduce((n,x)=>n+Number(x.quantity||0),0).toLocaleString('fa-IR')}</p></div><div className="track-items">{(order.items||[]).map((p,i)=><div key={i}><span>{p.name} × {p.quantity}</span><b>{Number(p.price).toLocaleString('fa-IR')} تومان</b></div>)}</div></div>:searched&&!error&&<div className="error">سفارشی با این شماره پیدا نشد.</div>}</main>}
