-- Yadak Land Iran: production database foundation
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint primary key,
  name text not null,
  category text not null,
  price bigint not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  image_url text,
  search_terms text[] not null default '{}',
  vehicles text[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.discount_codes (
  code text primary key,
  type text not null check (type in ('percent','fixed')),
  value bigint not null check (value > 0),
  min_order bigint not null default 0 check (min_order >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_name text not null,
  phone text not null,
  city text not null,
  address text not null,
  postal_code text not null,
  payment_method text not null,
  subtotal bigint not null check (subtotal >= 0),
  discount_code text,
  discount_amount bigint not null default 0 check (discount_amount >= 0),
  total bigint not null check (total >= 0),
  status text not null default 'در انتظار پرداخت',
  payment_status text not null default 'در انتظار',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null,
  product_name text not null,
  unit_price bigint not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0)
);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  status text not null,
  created_at timestamptz not null default now()
);

create index if not exists products_active_idx on public.products(active);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists order_history_order_id_idx on public.order_status_history(order_id);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.discount_codes enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles
for select to authenticated using (id = (select auth.uid()));

drop policy if exists "products public read" on public.products;
create policy "products public read" on public.products
for select to anon, authenticated using (active = true or (select public.is_admin()));

drop policy if exists "products admin insert" on public.products;
create policy "products admin insert" on public.products
for insert to authenticated with check ((select public.is_admin()));

drop policy if exists "products admin update" on public.products;
create policy "products admin update" on public.products
for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "products admin delete" on public.products;
create policy "products admin delete" on public.products
for delete to authenticated using ((select public.is_admin()));

drop policy if exists "discounts admin all" on public.discount_codes;
create policy "discounts admin all" on public.discount_codes
for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "orders admin read" on public.orders;
create policy "orders admin read" on public.orders
for select to authenticated using ((select public.is_admin()));

drop policy if exists "orders admin update" on public.orders;
create policy "orders admin update" on public.orders
for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "items admin read" on public.order_items;
create policy "items admin read" on public.order_items
for select to authenticated using ((select public.is_admin()));

drop policy if exists "history admin read" on public.order_status_history;
create policy "history admin read" on public.order_status_history
for select to authenticated using ((select public.is_admin()));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.create_order(
  p_customer jsonb,
  p_items jsonb,
  p_discount_code text default null,
  p_payment_method text default 'پرداخت آنلاین'
)
returns table(order_id bigint, order_number text, total bigint)
language plpgsql
security definer
set search_path = ''
as $$
declare
  item jsonb;
  v_product public.products%rowtype;
  v_id bigint;
  v_qty integer;
  v_subtotal bigint := 0;
  v_discount bigint := 0;
  v_total bigint := 0;
  v_code public.discount_codes%rowtype;
  v_order_id bigint;
  v_order_number text;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'سبد خرید خالی است';
  end if;

  for item in select * from jsonb_array_elements(p_items) loop
    v_id := (item->>'id')::bigint;
    v_qty := (item->>'quantity')::integer;
    if v_qty is null or v_qty <= 0 then raise exception 'تعداد کالا نامعتبر است'; end if;

    select * into v_product
    from public.products
    where id = v_id and active = true
    for update;

    if not found then raise exception 'محصول پیدا نشد'; end if;
    if v_product.stock < v_qty then raise exception 'موجودی محصول کافی نیست: %', v_product.name; end if;

    v_subtotal := v_subtotal + (v_product.price * v_qty);
  end loop;

  if nullif(trim(coalesce(p_discount_code,'')), '') is not null then
    select * into v_code from public.discount_codes
    where code = upper(trim(p_discount_code)) and active = true;

    if not found then raise exception 'کد تخفیف معتبر نیست'; end if;
    if v_subtotal < v_code.min_order then raise exception 'حداقل مبلغ خرید برای این کد رعایت نشده است'; end if;

    if v_code.type = 'percent' then
      v_discount := least(v_subtotal, floor(v_subtotal * v_code.value / 100.0)::bigint);
    else
      v_discount := least(v_subtotal, v_code.value);
    end if;
  end if;

  v_total := greatest(0, v_subtotal - v_discount);
  v_order_number := 'YL-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));

  insert into public.orders(
    order_number, customer_name, phone, city, address, postal_code,
    payment_method, subtotal, discount_code, discount_amount, total
  ) values (
    v_order_number,
    coalesce(p_customer->>'name',''),
    coalesce(p_customer->>'phone',''),
    coalesce(p_customer->>'city',''),
    coalesce(p_customer->>'address',''),
    coalesce(p_customer->>'postal',''),
    coalesce(p_payment_method,'پرداخت آنلاین'),
    v_subtotal,
    nullif(upper(trim(coalesce(p_discount_code,''))),''),
    v_discount,
    v_total
  ) returning id into v_order_id;

  for item in select * from jsonb_array_elements(p_items) loop
    v_id := (item->>'id')::bigint;
    v_qty := (item->>'quantity')::integer;

    select * into v_product from public.products where id = v_id for update;

    insert into public.order_items(order_id,product_id,product_name,unit_price,quantity)
    values(v_order_id,v_product.id,v_product.name,v_product.price,v_qty);

    update public.products
    set stock = stock - v_qty, updated_at = now()
    where id = v_id;
  end loop;

  insert into public.order_status_history(order_id,status)
  values(v_order_id,'در انتظار پرداخت');

  return query select v_order_id, v_order_number, v_total;
end;
$$;

revoke all on function public.create_order(jsonb,jsonb,text,text) from public;
grant execute on function public.create_order(jsonb,jsonb,text,text) to anon, authenticated;

create or replace function public.get_order_by_tracking(p_order_number text)
returns jsonb
language sql
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', o.id,
    'order_number', o.order_number,
    'created_at', o.created_at,
    'customer', jsonb_build_object(
      'name', o.customer_name, 'phone', o.phone, 'city', o.city,
      'address', o.address, 'postal', o.postal_code, 'payment', o.payment_method
    ),
    'subtotal', o.subtotal,
    'discount', case when o.discount_code is null then null else jsonb_build_object('code',o.discount_code,'amount',o.discount_amount) end,
    'total', o.total,
    'status', o.status,
    'payment_status', o.payment_status,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', oi.product_id, 'name', oi.product_name,
        'price', oi.unit_price, 'quantity', oi.quantity
      ) order by oi.id) from public.order_items oi where oi.order_id=o.id
    ), '[]'::jsonb)
  )
  from public.orders o
  where upper(o.order_number)=upper(trim(p_order_number))
  limit 1;
$$;

revoke all on function public.get_order_by_tracking(text) from public;
grant execute on function public.get_order_by_tracking(text) to anon, authenticated;

create or replace function public.set_order_status(p_order_id bigint, p_status text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then raise exception 'دسترسی غیرمجاز'; end if;
  update public.orders set status=p_status, updated_at=now() where id=p_order_id;
  insert into public.order_status_history(order_id,status) values(p_order_id,p_status);
end;
$$;

revoke all on function public.set_order_status(bigint,text) from public;
grant execute on function public.set_order_status(bigint,text) to authenticated;

-- Initial catalog copied from the current React demo.
insert into public.products(id,name,category,price,stock,image_url,vehicles,search_terms)
values
(1,'دیسک ترمز جلو پژو ۲۰۶ / ۲۰۷','ترمز',1850000,10,'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=700&q=80',array['پژو|۲۰۶','پژو|۲۰۷'],array['دیسک','ترمز','دیسک ترمز']),
(2,'فیلتر هوا پژو ۲۰۶','فیلتر',210000,10,'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=700&q=80',array['پژو|۲۰۶'],array['فیلتر','فیلتر هوا']),
(3,'باتری ۶۶ آمپر صبا باتری','برقی',2350000,10,'https://images.unsplash.com/photo-1603712725038-e9334ae8f39f?auto=format&fit=crop&w=700&q=80',array['ALL'],array['باتری','برقی']),
(4,'شمع موتور NGK پلاتینیوم','موتور',450000,10,'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=700&q=80',array['ALL'],array['شمع','موتور','NGK']),
(5,'لنت ترمز جلو کیا / هیوندای','ترمز',980000,10,'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c5?auto=format&fit=crop&w=700&q=80',array['کیا|سراتو','کیا|اسپورتیج','هیوندای|النترا','هیوندای|توسان'],array['لنت','ترمز']),
(6,'روغن موتور توتال 5W-30','روغن',1280000,10,'https://images.unsplash.com/photo-1635784063320-3e7b3b9b4b6f?auto=format&fit=crop&w=700&q=80',array['ALL'],array['روغن','روغن موتور']),
(7,'فیلتر روغن استاندارد','فیلتر',190000,10,'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=700&q=80',array['ALL'],array['فیلتر','فیلتر روغن']),
(8,'کمک فنر جلو خودرو','مصرفی',2650000,10,'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&w=700&q=80',array['پژو|۲۰۶','پژو|۲۰۷','پژو|۴۰۵','پژو|پارس','سایپا|پراید','سایپا|تیبا'],array['کمک فنر','کمک','فنر'])
on conflict (id) do nothing;


create or replace function public.preview_discount(p_code text, p_subtotal bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare v public.discount_codes%rowtype; v_amount bigint;
begin
  select * into v from public.discount_codes
  where code=upper(trim(coalesce(p_code,''))) and active=true;
  if not found then raise exception 'کد تخفیف معتبر نیست'; end if;
  if p_subtotal < v.min_order then raise exception 'حداقل مبلغ خرید برای این کد رعایت نشده است'; end if;
  if v.type='percent' then v_amount:=least(p_subtotal,floor(p_subtotal*v.value/100.0)::bigint);
  else v_amount:=least(p_subtotal,v.value); end if;
  return jsonb_build_object('code',v.code,'amount',v_amount,'type',v.type,'value',v.value);
end;
$$;
revoke all on function public.preview_discount(text,bigint) from public;
grant execute on function public.preview_discount(text,bigint) to anon, authenticated;
