create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  provider text not null default 'zarinpal',
  authority text,
  ref_id text,
  amount bigint not null check (amount >= 0),
  status text not null default 'pending' check (status in ('pending','success','failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(order_id, provider)
);

create unique index if not exists payment_transactions_authority_idx
on public.payment_transactions(authority) where authority is not null;

alter table public.payment_transactions enable row level security;

drop policy if exists "payment transactions admin read" on public.payment_transactions;
create policy "payment transactions admin read" on public.payment_transactions
for select to authenticated using ((select public.is_admin()));

revoke all on public.payment_transactions from anon, authenticated;
grant select on public.payment_transactions to authenticated;

create or replace function public.record_payment_result(
  p_order_id bigint,
  p_provider text,
  p_authority text,
  p_status text,
  p_ref_id text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old_status text;
begin
  if p_status not in ('success','failed') then
    raise exception 'وضعیت پرداخت نامعتبر است';
  end if;

  select status into v_old_status
  from public.payment_transactions
  where order_id=p_order_id and provider=p_provider
  for update;

  insert into public.payment_transactions(order_id,provider,authority,ref_id,amount,status)
  select p_order_id,p_provider,p_authority,p_ref_id,total,p_status
  from public.orders where id=p_order_id
  on conflict (order_id,provider) do update
    set authority=coalesce(excluded.authority,public.payment_transactions.authority),
        ref_id=coalesce(excluded.ref_id,public.payment_transactions.ref_id),
        status=case
          when public.payment_transactions.status='success' then 'success'
          else excluded.status
        end,
        updated_at=now();

  if coalesce(v_old_status,'')='success' then
    return;
  end if;

  if p_status='success' then
    update public.orders
      set payment_status='موفق',
          status=case when status='در انتظار پرداخت' then 'تأیید سفارش' else status end,
          updated_at=now()
    where id=p_order_id;
    insert into public.order_status_history(order_id,status)
    select p_order_id,'تأیید سفارش'
    where not exists (
      select 1 from public.order_status_history
      where order_id=p_order_id and status='تأیید سفارش'
    );
  else
    update public.orders
      set payment_status='ناموفق', updated_at=now()
    where id=p_order_id;
  end if;
end;
$$;

revoke all on function public.record_payment_result(bigint,text,text,text,text) from public;
grant execute on function public.record_payment_result(bigint,text,text,text,text) to service_role;
